name: Sync Fork from Upstream

on:
  schedule:
    - cron: '0 4 * * *'  # Täglich um 04:00 UTC
  workflow_dispatch:     # Manuelles Auslösen möglich

jobs:
  sync:
    name: Sync with upstream repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork's default branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/tianocore/edk2.git
          git fetch upstream

      - name: Rebase your default branch onto upstream
        run: |
          git checkout main  # oder 'master' – je nach Fork
          git rebase upstream/main

      - name: Push changes to your fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main --force-with-lease
